[package]
name = "rust-cli-load-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "mock-server",
    "project-1",
    "project-1-author-solution",
]


[dependencies]