[package]
name = "project-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
benchmark = { path = "benchmark" }
tokio = { version = "1.20", features = ["full"] }